### ISSUE TITLE
Generating HTML pages from API response of external API

### ISSUE THREAD

**Issue by Jordsan** [urbannator/cisc489_Topics_Artificial_Intelligence#5]
We are attempting to generate HTML pages that are derived from the response body of the request to the color clustering API we found. This will serve as a good visualization of where the locations in the photo contain the most ice.

**Comment by urbannator** [comment]
We will not be able to generate local html pages because this is not possible using javascript or typescript. Instead, we will be linking to an existing web page for the existing color clustering.
